### ISSUE TITLE
Pennyworth host reset fails with error

### ISSUE THREAD

**Issue by greygoo** [SUSE/pennyworth#43]
After some testign with initial hosts i decided to follow the instructions in thepennyworth README to get a host setup for pennyworth integration. Once it got installed, I set it up according to the README and added its information to ~/.pennyworth/hosts.yaml.

Then i changed someting on the hosts filesystem and tried to reset it using pennyworth host reset. This however just threw an error:

./bin/pennyworth host reset sles12_x86_64
Pennyworth experienced an unexpected error. Please file a bug report at https://github.com/SUSE/pennyworth/issues/new.
/usr/src/chuller/pennyworth/lib/remote_command_runner.rb:57:in `rescue in run': Execution of "ssh -o UserKnownHostsFile\=/dev/null -o StrictHostKeyChecking\=no root@192.168.121.104 LC_ALL\=C snapper create -c number --pre-number 1 --description pennyworth_snapshot" failed with status 1: Warning: Permanently added '192.168.121.104' (ECDSA) to the list of know (...). (ExecutionFailed)
Standard output:
 

Error output:
 Warning: Permanently added '192.168.121.104' (ECDSA) to the list of known hosts.
Unknown config.

        from /usr/src/chuller/pennyworth/lib/remote_command_runner.rb:38:in `run'
        from /usr/src/chuller/pennyworth/lib/host_runner.rb:63:in `cleanup'
        from /usr/src/chuller/pennyworth/lib/cli_host_controller.rb:81:in `reset'
        from /usr/src/chuller/pennyworth/lib/cli.rb:287:in `block (3 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from ./bin/pennyworth:25:in `<main>

**Comment by greygoo** [comment]
problem was a false positive, for some reason the changed entry for sles12-x86_64 was only used afterv the second run of pennyworth. The initial configured test machine had no btrfs and thus triggered the no config error. Closing the issue and keeping an eye on behaviour upon changes in the config file.
